<?php
/**
 * @var Marvelic\PromoLists\Block\Promotion\View $block
 */
 ?>
<div class="coupon-section">
    <?= $block->getChildHtml('promolist.promotion.coupon')?>
    <?php if ($block->getChildBlock('promolist.promotion.related.products')->getRelatedProducts()->getSize()): ?>
        <h3><?= __('Related Products') ?></h3>
        <?= $block->getChildHtml('promolist.promotion.related.products')?>
    <?php endif; ?>
</div>
