<?php
    //$helper = $this->helper('OnDemand\Catalog\Helper\Category');

    //@codingStandardsIgnoreFile

    /** @var PromotionList $block */

    use Magento\Framework\App\ObjectManager;
    use Magento\Framework\UrlInterface;
    use Marvelic\PromoLists\Api\Data\PromotionInterface;
    use Marvelic\PromoLists\Block\Promotion\PromotionList;
    $imgDefault = "http://dev.magento.abc/static/version1672116995/frontend/Magento/luma/en_US/images/logo.svg";
    $collection = $block->getPromotionCollection();
    $collection->setOrder('expire_at', 'ASC');
    $objectManager = ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $testBaseUrl = $storeManager->getStore()->getBaseUrl(UrlInterface::URL_TYPE_WEB);
    /** get id category of promotion current  */
    $cate = $objectManager->get('Magento\Framework\Registry')->registry('current_promolist_category');//get current product

    $entity_id = 1;
    if ($cate != null) {
        $cateCurr = $cate->getData();
        $entity_id = $cateCurr['entity_id'];
    }
    /** end get id category of promotion current  */

    $currentUrl = urldecode($this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]));

    $parsedCurrentUrl = explode('?', $currentUrl);

    $isFilterSubject = false;
//    $collection_arr = [];
    $isPromotionUrl = substr_count($currentUrl, "ondemand_promotion");
    $isCategoryUrl = substr_count($currentUrl, "category_ids");
    $isSubjectUrl = substr_count($currentUrl, "?subject");
    $isAllSubject = substr_count($currentUrl, "subject=all-subject");
    if (isset($parsedCurrentUrl[1])) {
        if ($isPromotionUrl == 0 && $isCategoryUrl == 0) {
            foreach ($parsedCurrentUrl as $key => $fruitsArr) {
                if ($key != 0) {
                    $attributeUrl = explode('=', $fruitsArr);
                    $attribute_codeUrl = $attributeUrl[0];
                    $attribute_valueUrl = $attributeUrl[1];
                    if ($attribute_codeUrl == "expire_date") {
                        if ($attribute_valueUrl == "asc") {
                            $collection->setOrder('expire_at', 'ASC');
                        } else {
                            $collection->setOrder('expire_at', 'des');
                        }
                    } else {
                        if ($attribute_codeUrl == "subject") {
                            if ($attribute_valueUrl == "all-subject") {
                                $arrAllSubject = [];
                                foreach ($collection as $promo) {
                                    $promotion = $promo->getSubject();
                                    if ($promotion == null) {
                                        $arrAllSubject[] = $promo;
                                    }
                                }
                                $collection = $arrAllSubject;
                            } else {
                                $arrSubject = [];
                                foreach ($collection as $promo) {
                                    $promotion = $promo->getSubject();
                                    if ($promotion == $attribute_valueUrl) {
                                        $arrSubject[] = $promo;
                                    }
                                }
                                $collection = $arrSubject;
                            }
                        }
                    }
                }
            }
        } else {
            foreach ($parsedCurrentUrl as $key => $fruitsArr) {
                if ($key != 0) {
                    $attributeUrl = explode('=', $fruitsArr);
                    $attribute_codeUrl = $attributeUrl[0];
                    $attribute_valueUrl = $attributeUrl[1];
                    if ($attribute_codeUrl == 'ondemand_promotion') {
                        $parsedCurrentUrl[] = $fruitsArr;
                        unset($parsedCurrentUrl[$key]);
                    }
                    if ($attribute_codeUrl == 'category_ids') {
                        $parsedCurrentUrl[] = $fruitsArr;
                        unset($parsedCurrentUrl[$key]);
                    }
                }
            }
            foreach ($parsedCurrentUrl as $key => $fruitsArr) {
                if ($key != 0) {
                    $attributeUrl = explode('=', $fruitsArr);
                    $attribute_codeUrl = $attributeUrl[0];
                    $attribute_valueUrl = $attributeUrl[1];
                    if ($attribute_codeUrl == 'ondemand_promotion' && $attribute_codeUrl == 'category_ids') {
                        $collection = $collection->addFieldToFilter($attribute_codeUrl, $attribute_valueUrl);
                    } else {
                        if ($attribute_codeUrl == "subject") {
                            if ($attribute_valueUrl == "all-subject") {
                                $arrAllSubject = [];
                                foreach ($collection as $promo) {
                                    $promotion = $promo->getSubject();
                                    if ($promotion == null) {
                                        $arrAllSubject[] = $promo;
                                    }
                                }
                                $collection = $arrAllSubject;
                            } else {
                                $arrSubject = [];
                                foreach ($collection as $promo) {
                                    $promotion = $promo->getSubject();
                                    if ($promotion == $attribute_valueUrl) {
                                        $arrSubject[] = $promo;
                                    }
                                }
                                $collection = $arrSubject;
                            }
                        } else {
                            if ($attribute_codeUrl == "expire_date") {
                                if ($attribute_valueUrl == "asc") {
                                    $collection->setOrder('expire_at', 'ASC');
                                } else {
                                    $collection->setOrder('expire_at', 'des');
                                }
                            } else {
                                if ($attribute_codeUrl == 'category_ids') {
                                    $arr3 = [];
                                    foreach ($collection as $promo) {
                                        $promotion = $promo->getPromoClass(); /*will return promotion array*/
                                        if ($promotion == $attribute_valueUrl) {
                                            $arr3[] = $promo;
                                        }
                                    }
                                    $collection = $arr3;
                                } else {
                                    if ($attribute_codeUrl == 'ondemand_promotion') {
                                        $arr4 = [];
                                        foreach ($collection as $promo) {
                                            $a = count($collection);
                                            $promotion = $promo->getPromotion(); /*will return promotion array*/
                                            if ($promotion == $attribute_valueUrl) {
                                                $arr4[] = $promo;
                                            }
                                        }
                                        $collection = $arr4;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    $objectManager = ObjectManager::getInstance();
    $attr_groups = [];
    $attr_groups["ondemand_promotion"] = [];
    $attr_groups["category_ids"] = [];
    $attr_groups["subject"] = [];
?>

<!-- container -->
<div class="toolbar toolbar-products">
    <?= $block->getViewModeHtml($collection); ?>
    <?= $block->getTotalAmountHtml($collection); ?>
    <?= $block->getSorterHtml($collection); ?>
</div>
<div class="home-blog-section container px-md-0 pt-4 pb-4">
    <div class="products wrapper list products-list">
        <?php if ($collection->count()): ?>
            <?php if ($block->getToolbarBlock()->getCurrentMode() === "list"): ?>
                <ol class="products list items product-items">
                    <?php /** @var PromotionInterface $promotion */ ?>
                    <?php foreach ($collection as $promotion): ?>
                        <li class="item product product-item" >
                            <div class="product-item-info">
                                <?php if ($promotion->getCoverImageUrl()): ?>
                                    <a href="<?= $promotion->getUrl() ?>" class="product photo product-item-photo">
                                    <span class="product-image-container product-image-container-1220" style="width: 240px;">
                                        <span class="product-image-wrapper" style="padding-bottom: 125%;">
                                            <img class="product-image-photo" src="<?= ($promotion->getCoverImageUrl()) ?>" alt="<?= $block->getFeaturedAlt($promotion) ?>" loading="lazy" width="240" height="300">
                                        </span>
                                    </span>
                                    </a>
                                <?php else:  ?>
                                    <a href="<?= $promotion->getUrl() ?>" class="product photo product-item-photo">
                                    <span class="product-image-container product-image-container-1220" style="width: 240px;">
                                        <span class="product-image-wrapper" style="padding-bottom: 125%;">
                                            <img class="product-image-photo" src="<?= ($promotion->getCoverImageUrl()) ?: $imgDefault ?>" alt="<?= $block->getFeaturedAlt($promotion) ?>" loading="lazy" width="240" height="300">
                                        </span>
                                    </span>
                                    </a>
                                <?php endif; ?>
                                <div class="product details product-item-details">
                                    <h4 class='max-line-3'>
                                        <a class ="text-secondary" href="<?= $promotion->getUrl() ?>" rel="bookmark">
                                            <?= $promotion->getName() ?>
                                        </a>
                                    </h4>
                                    <p><?=  $dayUpdate = $promotion->getExpirationOn();?> </p>
                                </div>
                            </div>
                        </li>
                    <?php endforeach ?>
                </ol>
            <?php else: ?>
                <div class="row">
                    <div class="content flex flex-wrap">
                        <?php /** @var PromotionInterface $promotion */ ?>
                        <?php foreach ($collection as $promotion): ?>
                            <div class="col-6 pb-2">
                                <div class="blog-item flex ha-center va-center">
                                    <div class="col-lg-4 col-4 mr-2">
                                        <?php if ($promotion->getCoverImageUrl()): ?>
                                            <a class="blog-img" href="<?= $promotion->getUrl() ?>">
                                                <img src="<?= $promotion->getCoverImageUrl() ?>" alt="<?= $block->getFeaturedAlt($promotion) ?>" >
                                            </a>
                                        <?php else: ?>
                                            <a class="blog-img" href="<?= $promotion->getUrl() ?>">
                                                <img src="<?= ($promotion->getCoverImageUrl()) ?: $imgDefault ?>" alt="<?= $block->getFeaturedAlt($promotion) ?>" >
                                            </a>
                                        <?php endif; ?>
                                    </div>
                                    <div class="col-lg-8 col-8">
                                        <h4 class='max-line-3'>
                                            <a class ="text-secondary" href="<?= $promotion->getUrl() ?>" rel="bookmark">
                                                <?= $promotion->getName() ?>
                                            </a>
                                        </h4>
                                        <p>
                                            <?=  $dayUpdate = $promotion->getExpirationOn();
                                            //echo $helper->DateThai("D/M/Y", $dayUpdate);
                                            ?>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach ?>
                    </div>
                </div>
            <?php endif ?>
            <?php if ($block->getPagerHtml()): ?>
                <div class="order-products-toolbar toolbar bottom"><?= $block->getChildBlock('pager')->setIsBottom(true)->toHtml(); ?></div>
            <?php endif ?>
        <?php else: ?>
            <div class="message notice">
                <div><?= __('There are no promotions available for this category.') ?></div>
            </div>
        <?php endif ?>
    </div>
</div>
<!-- end container -->

