<?php
//@codingStandardsIgnoreFile
/** @var $block Category */
use Marvelic\PromoLists\Block\Navigation\Category;

?>
    <!-- Filter Current -->
<div class="block filter" id="layered-filter-block" data-mage-init='
    {
        "collapsible":
        {
            "openedState": "active",
            "collapsible": true,
            "active": false,
            "collateral":
            {
                "openedState": "filter-active",
                "element": "body"
            }
        }
    }'>
    <div class="block-title filter-title" data-count="<?= /* @noEscape */ 2 ?>">
        <strong data-role="title"><?= $block->escapeHtml(__('Shop By')); ?></strong>
    </div>
    <div class="block-content filter-content">
        <?= $this->getLayout()
            ->createBlock('Marvelic\PromoLists\Block\Navigation\State')
            ->setTemplate('Marvelic_PromoLists::sidebar/state.phtml')
            ->toHtml();?>
        <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?= $block->escapeHtml(__('Shopping Options')) ?></strong>
        <div class="filter-options mage-accordion-disabled mb-2" id="narrow-by-list" data-role="content" role="tablist"
             data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": "0", "multipleCollapsible": true}}'
        >
            <!-- Sidebar Category   -->
            <?php if ($block->getCategoryPromotion()->count()): ?>
                <div data-role="collapsible" class="filter-options-item allow" role="presentation" data-collapsible="true">
                    <div data-role="title" class="filter-options-title" role="tab" aria-selected="false" aria-expanded="false" tabindex="0">Category</div>
                    <div data-role="content" class="filter-options-content" role="tabpanel" aria-hidden="false" style="">
                        <ol class="items">
                            <?php foreach ($block->getCategoryPromotion() as $category): ?>
                                <?php $count = $block->getPromotionByCatagory($category); ?>
                                    <?php if ($count->count()): ?>
                                    <li class="item">
                                        <a href="<?= $block->getUrlFilterAttributeCatePromotion($category->getId()) ?>" rel="nofollow"><?= $category->getName() ?>
                                            <span class="count">
                                                 <?= $count->count() ?>
                                                <span class="filter-count-label">item</span>
                                            </span>
                                        </a>
                                    </li>
                                    <?php endif; ?>
                            <?php endforeach ?>
                        </ol>
                    </div>
                </div>
            <?php endif; ?>
            <!-- Sidebar Attribute Allow   -->
            <div data-role="collapsible" class="filter-options-item allow" id="attribute_collapsible_hidden" role="presentation" data-collapsible="true">
                <div data-role="title" class="filter-options-title" role="tab" aria-selected="false" aria-expanded="false" tabindex="0">Attribute Allow</div>
                <div data-role="content" class="filter-options-content attribute_collapsible" role="tabpanel" aria-hidden="true" style="">
                    <ol class="items">
                        <?php foreach ($block->getAttributeAllow() as $attribute): ?>
                            <?php if (!$block->isAttributeFilter($attribute) && !empty($block->getCountAttributeByItem($attribute))): ?>
                                <li class="item">
                                    <a href="<?= $block->getUrlFilterAttribute($attribute); ?>"
                                       rel="nofollow"><?= $attribute->getFrontendLabel() ?><span class="count">
                                <?= $block->getCountAttributeByItem($attribute) ?><span class="filter-count-label">item</span></span>
                                    </a>
                                </li>
                            <?php endif; ?>
                        <?php endforeach ?>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    require(['jquery', 'Marvelic_PromoLists/js/promotion'], function($) {
    });
</script>
